version: '3.1'

services:
  server:
    build: ./server
    command: npm run dev
    environment:
      NODE_ENV: "development"
      PORT: "4201"
    volumes:
      - ./server:/code:delegated
      - /code/node_modules
    ports:
      - "4201:4201"

  client:
    build: ./client
    command: npm run start
    environment:
      TARGET_ENV: "dev"
    volumes:
      - ./client:/code:delegated
      - /code/node_modules
    ports:
      - "4200:4200"
    links:
      - server