name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run server tests
      run: echo "To run tests!"

    - name: Run client tests
      run: echo "To run tests!"